### ISSUE TITLE
Custom Model Voice Tearing

### ISSUE THREAD

**Issue by ttechkit** [Sage-of-Mirrors/Custom-Wind-Waker-Player-Models#2]
When using custom voices on a Wii using nintendont the audio tears awfully, but it only happens with custom voices. I don't know why.

**Comment by LagoLunatic** [comment]
Yeah this is some weird issue with the voices that apparently only happens on hardware. Medli's voice should be fine at least, the others need to be fixed somehow.

**Comment by ttechkit** [comment]
Ah ok I see, thanks!

**Comment by ttechkit** [comment]
I've tried the custom Ganondorf Model/Voice and it's working on OG hardware! Just thought I would bring this to your attention if you don't already know.
