### ISSUE TITLE
Creating/importing custom voices?

### ISSUE THREAD

**Issue by supersnackbros** [Sage-of-Mirrors/Custom-Wind-Waker-Player-Models#3]
Might links to tools and tutorials for custom voices be addes to the README? I've looked at both LagoLunatic and SageOfMirrors' pages and found nothing. Maybe I missed or this is something that should be obvious and I'm just a moron.

**Comment by LagoLunatic** [comment]
Join the randomizer discord server and check the pins in the #audio-mods channel.

I dunno much about audio hacking and have no interest in it, and people are still discovering new techniques for how to do it better, so I don't want to maintain a guide on audio hacking myself or it'll quickly become outdated and not of any use.
