### ISSUE TITLE
Zelda Model Does Not Change Dress Color

### ISSUE THREAD

**Issue by KLPD123** [Sage-of-Mirrors/Custom-Wind-Waker-Player-Models#4]
Hi, I was trying to play with Zelda's model, but changing her dress color only affects the lower portion of her dress and not the shirt. Below are screenshots of how she looks in game and then what was on the preview screen. How do I fix this?
![Screenshot (12)](https://user-images.githubusercontent.com/47219856/103028966-c9b3a700-4526-11eb-8c29-dbf47def81f5.png)
![Screenshot (13)](https://user-images.githubusercontent.com/47219856/103028971-cddfc480-4526-11eb-8c28-931599376a9f.png)

**Comment by KLPD123** [comment]
Hi, is this being worked on?

**Comment by LagoLunatic** [comment]
No idea, ask Sir Kilp in the discord server. I really don't think anyone but me checks this page so posting here won't do anything.

**Comment by LagoLunatic** [comment]
Fixed
